version: '3'
services:
  nginx:
    image: evild/alpine-nginx:1.9.15-openssl
    container_name: usuario_nginx
    volumes:
      - ./:/var/www/html/:ro
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8068:80
    links:
      - php
    depends_on:
      - php
  php:
    build: docker/php
    container_name: usuario_php
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - DB_TEST_DATABASE=tests
      - DB_PASSWORD=passwordcd
  db:
    image: mariadb:latest
    container_name: usuario_db
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password

networks:
  default:
    external:
      name: dev1
